// Generated by scripts/build-current-catalogue.mjs — do not edit.
//
// The Province's ministries and the exact wording of their marks, in both languages. Newlines are
// the line breaks the published artwork uses: it is hand-broken, not wrapped to a measure, so the
// breaks are part of the wording rather than something a layout rule can rediscover.
//
// The wording was read back off the published outlines themselves — see
// scripts/recover_current_names.py — which is also how the French names got here, since the
// Province publishes them only as artwork.

export const MINISTRIES = [
  {"code":"AF","en":"Ministry of\nAgriculture\nand Food","fr":"Ministère de\nl’Agriculture et de\nl’Alimentation"},
  {"code":"AG","en":"Ministry of\nAttorney General","fr":"Ministère du\nProcureur général"},
  {"code":"CFD","en":"Ministry of\nChildren and Family\nDevelopment","fr":"Ministère du\nDéveloppement de l’enfance\net de la famille"},
  {"code":"CITZ","en":"Ministry of\nCitizens’ Services","fr":"Ministère des\nServices aux citoyens"},
  {"code":"ECC","en":"Ministry of\nEducation and\nChild Care","fr":"Ministère de\nl’Éducation et des\nServices à la petite enfance"},
  {"code":"EMCR","en":"Ministry of\nEmergency Management\nand Climate Readiness","fr":"Ministère de\nla Gestion des urgences\net de la Préparation au climat"},
  {"code":"ECS","en":"Ministry of\nEnergy and Climate\nSolutions","fr":"Ministère de\nl’Énergie et des\nSolutions climatiques"},
  {"code":"ENV","en":"Ministry of\nEnvironment\nand Parks","fr":"Ministère de\nl’Environnement\net des Parcs"},
  {"code":"FIN","en":"Ministry of\nFinance","fr":"Ministère des\nFinances"},
  {"code":"FOR","en":"Ministry of\nForests","fr":"Ministère des\nForêts"},
  {"code":"HLTH","en":"Ministry of\nHealth","fr":"Ministère de\nla Santé"},
  {"code":"HMA","en":"Ministry of\nHousing and\nMunicipal Affairs","fr":"Ministère du\nLogement et des\nAffaires municipales"},
  {"code":"IRR","en":"Ministry of\nIndigenous Relations\nand Reconciliation","fr":"Ministère des\nRelations avec les Autochtones\net de la Réconciliation"},
  {"code":"INF","en":"Ministry of\nInfrastructure","fr":"Ministère de\nl’Infrastructure"},
  {"code":"JEG","en":"Ministry of\nJobs and\nEconomic Growth","fr":"Ministère des\nEmplois et de la\nCroissance économique"},
  {"code":"LBR","en":"Ministry of\nLabour","fr":"Ministère du\nTravail"},
  {"code":"MCM","en":"Ministry of\nMining and\nCritical Minerals","fr":"Ministère des\nMines et des\nMinéraux critiques"},
  {"code":"PSFS","en":"Ministry of\nPost-Secondary Education\nand Future Skills","fr":"Ministère de\nl’Éducation postsecondaire\net des Compétences futures"},
  {"code":"PSSG","en":"Ministry of\nPublic Safety and\nSolicitor General","fr":"Ministère de\nla Sécurité publique\net du Solliciteur général"},
  {"code":"SDPR","en":"Ministry of\nSocial Development\nand Poverty Reduction","fr":"Ministère du\nDéveloppement social\net de la Réduction de la pauvreté"},
  {"code":"TACS","en":"Ministry of\nTourism, Arts,\nCulture and Sport","fr":"Ministère du\nTourisme, des Arts, de\nla Culture et du Sport"},
  {"code":"TT","en":"Ministry of\nTransportation\nand Transit","fr":"Ministère des\nTransports et du\nTransport en commun"},
  {"code":"WLRS","en":"Ministry of\nWater, Land and\nResource Stewardship","fr":"Ministère de\nl’Intendance de l’eau, des terres\net des ressources"}
]

/** Marks whose published line breaks could not be read, and are wrapped by this project instead. */
export const WRAPPED_BY_US = ["ecs-en","hma-en","inf-en","wlrs-en"]

export const MINISTRY_CODES = MINISTRIES.map((ministry) => ministry.code)

/** One ministry's wording, or undefined. Codes are matched case-insensitively. */
export const findMinistry = (code) => MINISTRIES
  .find((ministry) => ministry.code.toLowerCase() === String(code).toLowerCase())
