// Generated by scripts/build-current-catalogue.mjs — do not edit.
//
// The Province's ministries and the wording of their marks, in both languages, read back off the
// published outlines themselves — see scripts/recover_current_names.py. That is also how the
// French names got here, since the Province publishes them only as artwork.
//
// The wording is plain: where the line breaks go is decided by the rules in
// src/current/currentLayout.js, which reproduce 44 of the 46 published marks exactly. The other
// two carry the Province's own breaks as newlines, because their artwork disagrees with its own
// rules and the artwork wins.

export const MINISTRIES = [
  {"code":"AF","en":"Ministry of Agriculture and Food","fr":"Ministère de\nl’Agriculture et de\nl’Alimentation"},
  {"code":"AG","en":"Ministry of Attorney General","fr":"Ministère du Procureur général"},
  {"code":"CFD","en":"Ministry of Children and Family Development","fr":"Ministère du Développement de l’enfance et de la famille"},
  {"code":"CITZ","en":"Ministry of Citizens’ Services","fr":"Ministère des Services aux citoyens"},
  {"code":"ECC","en":"Ministry of Education and Child Care","fr":"Ministère de\nl’Éducation et des\nServices à la petite enfance"},
  {"code":"EMCR","en":"Ministry of Emergency Management and Climate Readiness","fr":"Ministère de la Gestion des urgences et de la Préparation au climat"},
  {"code":"ECS","en":"Ministry of Energy and Climate Solutions","fr":"Ministère de l’Énergie et des Solutions climatiques"},
  {"code":"ENV","en":"Ministry of Environment and Parks","fr":"Ministère de l’Environnement et des Parcs"},
  {"code":"FIN","en":"Ministry of Finance","fr":"Ministère des Finances"},
  {"code":"FOR","en":"Ministry of Forests","fr":"Ministère des Forêts"},
  {"code":"HLTH","en":"Ministry of Health","fr":"Ministère de la Santé"},
  {"code":"HMA","en":"Ministry of Housing and Municipal Affairs","fr":"Ministère du Logement et des Affaires municipales"},
  {"code":"IRR","en":"Ministry of Indigenous Relations and Reconciliation","fr":"Ministère des Relations avec les Autochtones et de la Réconciliation"},
  {"code":"INF","en":"Ministry of Infrastructure","fr":"Ministère de l’Infrastructure"},
  {"code":"JEG","en":"Ministry of Jobs and Economic Growth","fr":"Ministère des Emplois et de la Croissance économique"},
  {"code":"LBR","en":"Ministry of Labour","fr":"Ministère du Travail"},
  {"code":"MCM","en":"Ministry of Mining and Critical Minerals","fr":"Ministère des Mines et des Minéraux critiques"},
  {"code":"PSFS","en":"Ministry of Post-Secondary Education and Future Skills","fr":"Ministère de l’Éducation postsecondaire et des Compétences futures"},
  {"code":"PSSG","en":"Ministry of Public Safety and Solicitor General","fr":"Ministère de la Sécurité publique et du Solliciteur général"},
  {"code":"SDPR","en":"Ministry of Social Development and Poverty Reduction","fr":"Ministère du Développement social et de la Réduction de la pauvreté"},
  {"code":"TACS","en":"Ministry of Tourism, Arts, Culture and Sport","fr":"Ministère du Tourisme, des Arts, de la Culture et du Sport"},
  {"code":"TT","en":"Ministry of Transportation and Transit","fr":"Ministère des Transports et du Transport en commun"},
  {"code":"WLRS","en":"Ministry of Water, Land and Resource Stewardship","fr":"Ministère de l’Intendance de l’eau, des terres et des ressources"}
]

/** Marks whose breaks the rules do not reproduce, so their wording states them. */
export const BREAKS_STATED = ["af-fr","ecc-fr"]

/** Marks whose published breaks could not be read at all, so these are the rules' own. */
export const UNVERIFIED = []

export const MINISTRY_CODES = MINISTRIES.map((ministry) => ministry.code)

/** One ministry's wording, or undefined. Codes are matched case-insensitively. */
export const findMinistry = (code) => MINISTRIES
  .find((ministry) => ministry.code.toLowerCase() === String(code).toLowerCase())
