// The Government of British Columbia as it stands today — the part of the diagram only the
// present can fill in.
//
// Assembled 2026-09-25 from official pages: the Executive Council and Deputy Ministers' Council
// lists on gov.bc.ca, the Crown corporations' Budget 2026 service plans and 2025/26 annual reports,
// leg.bc.ca's statutory officers, the courts' and health authorities' own leadership pages, and the
// 2025/26 Public Accounts for staffing. Each figure is what those sources said on that day; a
// cabinet shuffle, a new appointment or the election of 24 October 2026 will date it, and the view
// says how old it is.
//
// `employees` is the Public Accounts' 2025/26 full-time-equivalent staffing — paid hours over
// full-time hours, General Fund salaries only — not a headcount. `established` is the year a body
// is known to have begun, which is what lets it appear on the timeline before today; it is null
// where no source gave one, and such a body is shown in the present only.

/** The day these facts were checked. */
export const CURRENT_AS_OF = '2026-09-25'

/** Who holds what in the Legislature itself. */
export const LEGISLATURE_TODAY = {
  speaker: { title: 'Speaker', person: 'Raj Chouhan', since: '2020-12-07' },
  clerk: { title: 'Clerk of the Legislative Assembly', person: 'Kate Ryan-Lloyd', since: '2020-03-03' }
}

const OFFICER = { kind: 'officer', branch: 'legislative', ring: 'oversight' }
const COURT = { kind: 'court', branch: 'judicial' }
const HEALTH = { kind: 'health-authority', branch: 'executive', ring: 'outer', responsibleMinistry: 'Ministry of Health' }
const CROWN = { kind: 'crown-corporation', branch: 'executive', ring: 'outer' }
const CENTRAL = { kind: 'central-agency', branch: 'executive', ring: 'oversight' }

/**
 * Every body around the ministries, with the ministry that answers for it where there is one.
 * `responsibleMinistry` is a ministry's name as the Province writes it.
 */
export const CURRENT_BODIES = [
  // ── Central agencies ──────────────────────────────────────────────────────────────────────────
  { ...CENTRAL, id: 'office-of-the-premier', name: 'Office of the Premier', employees: 93, established: null, officialUrl: 'https://www2.gov.bc.ca/gov/content/governments/organizational-structure/office-of-the-premier', description: 'The Premier’s own office and the Cabinet Secretariat, including the Intergovernmental Relations Secretariat. A Minister of State for Local Governments and Rural Communities (Brittny Anderson, since 2024-11-18) is attached to it.' },
  { ...CENTRAL, id: 'bc-public-service-agency', name: 'BC Public Service Agency', employees: 648, established: null, head: { title: 'Deputy Minister, Head of the BC Public Service Agency', person: 'Deb Godfrey' }, officialUrl: 'https://www2.gov.bc.ca/gov/content/careers-myhr', description: 'The public service’s employer: hiring, pay, labour relations and learning for some 40,000 employees. Since 30 June 2026 its head also carries out the Merit Commissioner’s staffing reviews, the independent office having been abolished by the Budget Measures Implementation Act, 2026.' },
  { ...CENTRAL, id: 'government-communications-and-public-engagement', name: 'Government Communications and Public Engagement', established: null, officialUrl: 'https://news.gov.bc.ca', description: 'Government’s communications, news releases and public engagement, budgeted as a vote within the Ministry of Finance.' },

  // ── Officers of the Legislature ───────────────────────────────────────────────────────────────
  { ...OFFICER, id: 'auditor-general', name: 'Auditor General of British Columbia', head: { title: 'Auditor General', person: 'Bridget Parrish', since: '2025-12-01' }, established: 1977, officialUrl: 'https://www.oag.bc.ca', description: 'Audits the government’s financial statements and the performance of its programs, reporting to the Legislative Assembly.' },
  { ...OFFICER, id: 'ombudsperson', name: 'Ombudsperson', head: { title: 'Ombudsperson', person: 'Sandy Hermiston', since: '2026-01-31' }, established: 1979, officialUrl: 'https://bcombudsperson.ca', description: 'Investigates complaints of unfair treatment by provincial public bodies.' },
  { ...OFFICER, id: 'information-and-privacy-commissioner', name: 'Information and Privacy Commissioner', head: { title: 'Information and Privacy Commissioner and Registrar of Lobbyists', person: 'Michael Harvey', since: '2024-05' }, established: 1993, officialUrl: 'https://www.oipc.bc.ca', description: 'Oversees the access-to-information and privacy laws; the Commissioner is also Registrar of Lobbyists.' },
  { ...OFFICER, id: 'chief-electoral-officer', name: 'Elections BC', head: { title: 'Chief Electoral Officer', person: 'Shipra Verma', since: '2025-11-12' }, established: 1947, officialUrl: 'https://elections.bc.ca', description: 'Runs provincial elections, by-elections, referenda and recall and initiative petitions. An independent officer of the Legislature since 1995.' },
  { ...OFFICER, id: 'conflict-of-interest-commissioner', name: 'Conflict of Interest Commissioner', head: { title: 'Conflict of Interest Commissioner', person: 'Jeffrey Schnoor', since: '2026-01-05' }, established: 1990, officialUrl: 'https://coibc.ca', description: 'Advises Members on, and investigates, conflicts between their public duties and private interests.' },
  { ...OFFICER, id: 'representative-for-children-and-youth', name: 'Representative for Children and Youth', head: { title: 'Representative for Children and Youth', person: 'Jennifer Charlesworth', since: '2018' }, established: 2007, officialUrl: 'https://rcybc.ca', description: 'Advocates for children and youth, and monitors and reviews the child-serving system.' },
  { ...OFFICER, id: 'human-rights-commissioner', name: 'Human Rights Commissioner', head: { title: 'Human Rights Commissioner', person: 'Kasari Govender', since: '2019-09-03' }, established: 2019, officialUrl: 'https://bchumanrights.ca', description: 'Promotes and protects human rights in British Columbia.' },
  { ...OFFICER, id: 'police-complaint-commissioner', name: 'Police Complaint Commissioner', head: { title: 'Police Complaint Commissioner', person: 'Prabhu Rajan', since: '2024-02-21' }, established: 1998, officialUrl: 'https://opcc.bc.ca', description: 'Oversees complaints and investigations about municipal police in British Columbia.' },

  // ── Courts ────────────────────────────────────────────────────────────────────────────────────
  { ...COURT, ring: 'inner', id: 'court-of-appeal', name: 'Court of Appeal for British Columbia', head: { title: 'Chief Justice of British Columbia', person: 'Leonard Marchand', since: '2023-12-07' }, established: 1909, officialUrl: 'https://www.bccourts.ca/Court_of_Appeal/', description: 'The province’s highest court, hearing appeals from the Supreme Court and some tribunals. Its justices are appointed by the federal government.' },
  { ...COURT, ring: 'outer', id: 'supreme-court', name: 'Supreme Court of British Columbia', head: { title: 'Chief Justice', person: 'Ronald A. Skolrood', since: '2024-10-15' }, established: 1870, officialUrl: 'https://www.bccourts.ca/supreme_court/', description: 'The province’s superior trial court. Its justices are appointed by the federal government.' },
  { ...COURT, ring: 'outer', id: 'provincial-court', name: 'Provincial Court of British Columbia', head: { title: 'Chief Judge', person: 'Melissa Gillespie', since: '2018-10-19' }, established: 1969, officialUrl: 'https://www.provincialcourt.bc.ca', description: 'Hears most criminal, family, small-claims and youth cases, in more than 80 locations. Its judges are appointed by the Province on the Judicial Council’s recommendation.' },

  // ── Health authorities ────────────────────────────────────────────────────────────────────────
  { ...HEALTH, id: 'northern-health', name: 'Northern Health', head: { title: 'President and CEO', person: 'Ciro Panessa', since: '2023-09-05' }, established: 2001, officialUrl: 'https://www.northernhealth.ca', description: 'Regional health authority for northern British Columbia.' },
  { ...HEALTH, id: 'interior-health', name: 'Interior Health', head: { title: 'President and CEO', person: 'Sylvia Weir', since: '2025-10-09' }, established: 2001, officialUrl: 'https://www.interiorhealth.ca', description: 'Regional health authority for the southern interior.' },
  { ...HEALTH, id: 'fraser-health', name: 'Fraser Health', head: { title: 'President and CEO', person: 'Dermot Kelly', since: '2025-08-18' }, established: 2001, officialUrl: 'https://www.fraserhealth.ca', description: 'Regional health authority serving over two million people from Burnaby to Hope.' },
  { ...HEALTH, id: 'vancouver-coastal-health', name: 'Vancouver Coastal Health', head: { title: 'President and CEO', person: 'Vivian Eliopoulos' }, established: 2001, officialUrl: 'https://www.vch.ca', description: 'Regional health authority for Vancouver, Richmond and the coast; the province’s largest academic and quaternary-care authority.' },
  { ...HEALTH, id: 'island-health', name: 'Island Health', head: { title: 'President and CEO', person: 'Kathy MacNeil', since: '2018-02-19' }, established: 2001, officialUrl: 'https://www.islandhealth.ca', description: 'Regional health authority for Vancouver Island, the Gulf Islands and part of the mainland coast.' },
  { ...HEALTH, id: 'provincial-health-services-authority', name: 'Provincial Health Services Authority', shortName: 'PHSA', head: { title: 'President and CEO', person: 'Paul Mochrie', since: '2026-06' }, established: 2001, officialUrl: 'https://www.phsa.ca', description: 'The one health authority with a province-wide mandate, including BC Cancer and BC Emergency Health Services.' },
  { ...HEALTH, responsibleMinistry: null, id: 'first-nations-health-authority', name: 'First Nations Health Authority', shortName: 'FNHA', head: { title: 'CEO', person: 'Monica McAlduff', since: '2025-03-01' }, established: 2013, officialUrl: 'https://www.fnha.ca', description: 'The first province-wide First Nations health authority in Canada, which took over Health Canada’s First Nations programs in British Columbia in 2013. It is governed by First Nations, not by the Province.' },

  // ── Crown corporations ────────────────────────────────────────────────────────────────────────
  { ...CROWN, "id": "bc-hydro", "name": "British Columbia Hydro and Power Authority", "shortName": "BC Hydro", "responsibleMinistry": "Ministry of Energy and Climate Solutions", "head": {"title": "President and CEO", "person": "Charlotte Mitha"}, "chair": "Glen Clark", "established": 1962, "officialUrl": "https://www.bchydro.com", "description": "Generates, buys, distributes and sells electricity across most of the province."},
  { ...CROWN, "id": "icbc", "name": "Insurance Corporation of British Columbia", "shortName": "ICBC", "responsibleMinistry": "Ministry of Attorney General", "head": {"title": "President and CEO", "person": "Jason McDaniel"}, "chair": "Catherine Holt", "established": 1973, "officialUrl": "https://www.icbc.com", "description": "Universal public auto insurance, driver licensing and vehicle registration."},
  { ...CROWN, "id": "bclc", "name": "British Columbia Lottery Corporation", "shortName": "BCLC", "responsibleMinistry": "Ministry of Finance", "head": {"title": "President and CEO", "person": "Pat Davis"}, "chair": "Greg Moore", "established": 1984, "officialUrl": "https://www.bclc.com", "description": "Runs lottery, casino and online gambling."},
  { ...CROWN, "id": "bc-housing", "name": "British Columbia Housing Management Commission", "shortName": "BC Housing", "responsibleMinistry": "Ministry of Housing and Municipal Affairs", "head": {"title": "President and CEO", "person": "Vincent Tong"}, "established": 1967, "officialUrl": "https://www.bchousing.org", "description": "Develops, manages and funds subsidized housing, and runs BC Builds."},
  { ...CROWN, "id": "bc-transit", "name": "British Columbia Transit", "shortName": "BC Transit", "responsibleMinistry": "Ministry of Transportation and Transit", "head": {"title": "President and CEO", "person": "Erinn Pinkerton"}, "chair": "Sherri Bell", "established": 1998, "officialUrl": "https://www.bctransit.com", "description": "Public transit across the province outside Metro Vancouver."},
  { ...CROWN, "id": "bc-assessment", "name": "British Columbia Assessment Authority", "shortName": "BC Assessment", "responsibleMinistry": "Ministry of Finance", "head": {"title": "President and CEO", "person": "Jason Grant"}, "chair": "Gina Pala", "established": 1974, "officialUrl": "https://www.bcassessment.ca", "description": "Produces the annual assessments of every property in the province."},
  { ...CROWN, "id": "bc-securities-commission", "name": "British Columbia Securities Commission", "shortName": "BCSC", "responsibleMinistry": "Ministry of Finance", "head": {"title": "President and CEO", "person": "Brenda M. Leong"}, "chair": "Brenda M. Leong", "established": 1995, "officialUrl": "https://www.bcsc.bc.ca", "description": "Regulates the province’s capital markets."},
  { ...CROWN, "id": "bc-financial-services-authority", "name": "BC Financial Services Authority", "shortName": "BCFSA", "responsibleMinistry": "Ministry of Finance", "head": {"title": "President and CEO", "person": "Tolga Yalkin"}, "chair": "Sandra Heath", "established": 2019, "officialUrl": "https://www.bcfsa.ca", "description": "Regulates credit unions, insurers, trust companies, pension plans, mortgage brokers and real estate."},
  { ...CROWN, "id": "innovate-bc", "name": "Innovate BC", "responsibleMinistry": "Ministry of Finance", "head": {"title": "President and CEO", "person": "Peter Cowan"}, "chair": "Jessie Adcock", "established": 2018, "officialUrl": "https://innovatebc.ca", "description": "The Province’s innovation and commercialization agency."},
  { ...CROWN, "id": "columbia-basin-trust", "name": "Columbia Basin Trust", "responsibleMinistry": "Ministry of Energy and Climate Solutions", "head": {"title": "President and CEO", "person": "Johnny Strilaeff"}, "chair": "Susan Clovechok", "established": 1995, "officialUrl": "https://ourtrust.org", "description": "Invests for the economic, environmental and social benefit of the Columbia Basin."},
  { ...CROWN, "id": "columbia-power", "name": "Columbia Power Corporation", "shortName": "Columbia Power", "responsibleMinistry": "Ministry of Energy and Climate Solutions", "head": {"title": "President and CEO", "person": "Johnny Strilaeff"}, "chair": "John Stephens", "established": null, "officialUrl": "https://columbiapower.org", "description": "Owns and operates hydro projects in the Columbia Basin, jointly with Columbia Basin Trust."},
  { ...CROWN, "id": "bc-energy-regulator", "name": "British Columbia Energy Regulator", "shortName": "BCER", "responsibleMinistry": "Ministry of Energy and Climate Solutions", "head": {"title": "President and CEO", "person": "Michelle Carr"}, "chair": "Natascha Kiernan", "established": 1998, "officialUrl": "https://www.bc-er.ca", "description": "Regulates energy activity, from oil and gas wells to pipelines and reclamation. Formerly the BC Oil and Gas Commission."},
  { ...CROWN, "id": "destination-bc", "name": "Destination BC Corp.", "shortName": "Destination BC", "responsibleMinistry": "Ministry of Tourism, Arts, Culture and Sport", "head": {"title": "President and CEO", "person": "Richard Porges"}, "chair": "Ingrid Jarrett", "established": 2012, "officialUrl": "https://www.destinationbc.ca", "description": "Markets the province as a tourism destination."},
  { ...CROWN, "id": "bc-pavilion-corporation", "name": "British Columbia Pavilion Corporation", "shortName": "PavCo", "responsibleMinistry": "Ministry of Tourism, Arts, Culture and Sport", "head": {"title": "President and CEO", "person": "Rehana Din"}, "chair": "Gwendolyn Point", "established": 2008, "officialUrl": "https://www.bcpavco.com", "description": "Owns and operates BC Place and the Vancouver Convention Centre."},
  { ...CROWN, "id": "knowledge-network", "name": "Knowledge Network Corporation", "shortName": "Knowledge Network", "responsibleMinistry": "Ministry of Tourism, Arts, Culture and Sport", "head": {"title": "President and CEO", "person": "Michelle van Beusekom"}, "chair": "Satwinder Bains", "established": null, "officialUrl": "https://www.knowledge.ca", "description": "Viewer-supported, commercial-free public broadcaster."},
  { ...CROWN, "id": "royal-bc-museum", "name": "Royal British Columbia Museum Corporation", "shortName": "Royal BC Museum", "responsibleMinistry": "Ministry of Tourism, Arts, Culture and Sport", "head": {"title": "President and CEO", "person": "Allison Bond"}, "chair": "Stan Chung", "established": 2003, "officialUrl": "https://royalbcmuseum.bc.ca", "description": "Collects and preserves the province’s natural and human history."},
  { ...CROWN, "id": "bc-games-society", "name": "BC Games Society", "shortName": "BC Games", "responsibleMinistry": "Ministry of Tourism, Arts, Culture and Sport", "head": {"title": "President and CEO", "person": "Alison Noble"}, "chair": "Francis Cheung", "established": null, "officialUrl": "https://www.bcgames.org", "description": "Runs the BC Winter and Summer Games and prepares Team BC."},
  { ...CROWN, "id": "transportation-investment-corporation", "name": "Transportation Investment Corporation", "shortName": "TI Corp", "responsibleMinistry": "Ministry of Transportation and Transit", "head": {"title": "President and CEO", "person": "Amanda Farrell"}, "chair": "Sabine Feulgen", "established": 2008, "officialUrl": "https://www.ticorp.ca", "description": "Delivers major transportation projects such as the Pattullo Bridge and Broadway Subway."},
  { ...CROWN, "id": "bc-infrastructure-benefits", "name": "BC Infrastructure Benefits Inc.", "shortName": "BCIB", "responsibleMinistry": "Ministry of Infrastructure", "head": {"title": "President and CEO", "person": "Irene Kerr"}, "chair": "Cynthia Morton", "established": 2018, "officialUrl": "https://www.bcib.ca", "description": "Employs the workforce on public projects under the Community Benefits Agreement."},
  { ...CROWN, "id": "infrastructure-bc", "name": "Infrastructure BC Inc.", "shortName": "Infrastructure BC", "responsibleMinistry": "Ministry of Infrastructure", "head": {"title": "President and CEO", "person": "Mark Liedemann"}, "chair": "Connie Fair", "established": 2002, "officialUrl": "https://www.infrastructurebc.com", "description": "Helps the public sector plan and procure complex capital projects. Formerly Partnerships BC."},
  { ...CROWN, "id": "inbc", "name": "InBC Investment Corp.", "shortName": "InBC", "responsibleMinistry": "Ministry of Jobs and Economic Growth", "head": {"title": "President and CEO", "person": "Jill Earthy"}, "chair": "Suzanne Trottier", "established": 2021, "officialUrl": "https://www.inbcinvestment.ca", "description": "Manages the Province’s strategic investment fund for high-growth companies."},
  { ...CROWN, "id": "forestry-innovation-investment", "name": "Forestry Innovation Investment Ltd.", "shortName": "FII", "responsibleMinistry": "Ministry of Forests", "head": {"title": "President and CEO", "person": "Michael Loseth"}, "chair": "Rick Doman", "established": null, "officialUrl": "https://www.bcfii.ca", "description": "Market development for the province’s forest products."},
  { ...CROWN, "id": "forest-enhancement-society", "name": "Forest Enhancement Society of BC", "shortName": "FESBC", "responsibleMinistry": "Ministry of Forests", "head": null, "chair": "Ken Day", "established": 2016, "officialUrl": "https://www.fesbc.ca", "description": "Funds wildfire risk reduction, forest rehabilitation and better use of fibre."},
  { ...CROWN, "id": "legal-aid-bc", "name": "Legal Aid BC", "responsibleMinistry": "Ministry of Attorney General", "head": {"title": "President and CEO", "person": "Wendy Jackson"}, "chair": "Thomas Arbogast", "established": 1979, "officialUrl": "https://legalaid.bc.ca", "description": "Legal information, advice and representation for people with low incomes. Formerly the Legal Services Society."},
  { ...CROWN, "id": "bc-family-maintenance-agency", "name": "BC Family Maintenance Agency Ltd.", "shortName": "BCFMA", "responsibleMinistry": "Ministry of Attorney General", "head": {"title": "President and CEO", "person": "Joanne Hanson"}, "chair": "Johanne Blenkin", "established": 2019, "officialUrl": "https://www.bcfma.ca", "description": "Helps families collect the child and spousal support they are owed."},
  { ...CROWN, "id": "skilledtradesbc", "name": "SkilledTradesBC", "responsibleMinistry": "Ministry of Post-Secondary Education and Future Skills", "head": {"title": "President and CEO", "person": "Shelley Gray"}, "chair": "Paul Vogt", "established": 2004, "officialUrl": "https://skilledtradesbc.ca", "description": "Runs the skilled trades system: apprenticeships, credentials and standards. Formerly the Industry Training Authority."},
  { ...CROWN, "id": "bc-council-for-international-education", "name": "British Columbia Council for International Education", "shortName": "BCCIE", "responsibleMinistry": "Ministry of Post-Secondary Education and Future Skills", "head": {"title": "President and CEO", "person": "Randall Martin"}, "chair": "Ajay Patel", "established": null, "officialUrl": "https://www.bccie.bc.ca", "description": "Supports international education across schools, colleges, universities and language schools."},
  { ...CROWN, "id": "community-living-bc", "name": "Community Living British Columbia", "shortName": "CLBC", "responsibleMinistry": "Ministry of Social Development and Poverty Reduction", "head": {"title": "President and CEO", "person": "Ross Chilton"}, "chair": "Shane Simpson", "established": 2005, "officialUrl": "https://www.communitylivingbc.ca", "description": "Funds supports and services for adults with developmental disabilities."},
  { ...CROWN, "id": "first-peoples-cultural-council", "name": "First Peoples' Cultural Council", "shortName": "FPCC", "responsibleMinistry": "Ministry of Indigenous Relations and Reconciliation", "head": {"title": "President and CEO", "person": "Tracey Herbert"}, "chair": "Carla George", "established": null, "officialUrl": "https://www.fpcc.ca", "description": "First Nations-run Crown corporation supporting the revitalization of First Nations languages, arts and cultures."},
  { kind: 'agency', branch: 'executive', ring: 'outer', "id": "liquor-distribution-branch", "name": "Liquor Distribution Branch", "shortName": "LDB", "responsibleMinistry": "Ministry of Agriculture and Food", "head": {"title": "General Manager and CEO (interim)", "person": "Erin McEwan"}, "established": 1921, "officialUrl": "https://www.bcldb.com", "description": "A branch of government rather than a corporation: the wholesale distributor of liquor and non-medical cannabis, and the operator of BC Liquor Stores and BC Cannabis Stores."}
]

/**
 * Each current ministry's minister, deputy, ministers of state and staffing, keyed by the ministry's
 * slug. The minister is the one appointed to the portfolio; two were on leave on the day checked —
 * Jessie Sunner (Post-Secondary Education, parental leave from 31 July 2026, covered by Jennifer
 * Whiteside) and Brenda Bailey (Jobs and Economic Growth, medical leave, covered by Adrian Dix).
 */
export const CURRENT_MINISTERS = {
  "ministry-of-agriculture-and-food": {"shortName": "AF", "minister": {"title": "Minister of Agriculture and Food", "person": "Lana Popham", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Michelle Koski"}, "ministersOfState": [], "employees": 513, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/agriculture", "description": "Responsible for B.C.'s agriculture, food and seafood sectors, including food security and farmland policy."},
  "ministry-of-attorney-general": {"shortName": "AG", "minister": {"title": "Attorney General and Deputy Premier", "person": "Niki Sharma", "since": "2022-12-07"}, "deputy": {"title": "Deputy Attorney General", "person": "Barbara Carmichael"}, "ministersOfState": [], "employees": 4973, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/attorney-general", "description": "Responsible for the justice system, legal services to government and court administration; the Attorney General is also Deputy Premier (since Nov 18, 2024)."},
  "ministry-of-children-and-family-development": {"shortName": "MCFD", "minister": {"title": "Minister of Children and Family Development", "person": "Jodie Wickens", "since": "2024-12-10"}, "deputy": {"title": "Deputy Minister", "person": "Keith M. Godin"}, "ministersOfState": [], "employees": 4831, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/children-and-family-development", "description": "Responsible for child protection, child and youth mental health, youth justice and services for children and youth with support needs."},
  "ministry-of-citizens-services": {"shortName": "CITZ", "minister": {"title": "Minister of Citizens' Services", "person": "Diana Gibson", "since": "2025-07-17"}, "deputy": {"title": "Deputy Minister", "person": "Hayden Lansdell"}, "ministersOfState": [], "employees": 3434, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/citizens-services", "description": "Responsible for Service BC, government digital and IT services, procurement and information access."},
  "ministry-of-education-and-child-care": {"shortName": "ECC", "minister": {"title": "Minister of Education and Child Care", "person": "Lisa Beare", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Kathryn Krishna"}, "ministersOfState": [], "employees": 882, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/education", "description": "Responsible for the K-12 education system and child care."},
  "ministry-of-emergency-management-and-climate-readiness": {"shortName": "EMCR", "minister": {"title": "Minister of Emergency Management and Climate Readiness", "person": "Kelly Greene", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Teresa Dobmeier"}, "ministersOfState": [], "employees": 364, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/emergency-management-and-climate-readiness", "description": "Responsible for emergency management, disaster response and recovery, and climate-hazard readiness."},
  "ministry-of-energy-and-climate-solutions": {"shortName": "ECS", "minister": {"title": "Minister of Energy and Climate Solutions and Minister responsible for Francophone Affairs", "person": "Adrian Dix", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Peter Pokorny"}, "ministersOfState": [], "employees": 315, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/energy", "description": "Created Nov 2024; responsible for electricity, alternative energy and petroleum resource sectors and energy/climate policy, including the Climate Action Secretariat and oversight of BC Hydro's capital plan."},
  "ministry-of-environment-and-parks": {"shortName": "ENV", "minister": {"title": "Minister of Environment and Parks", "person": "Tamara Davidson", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Kevin Jardine"}, "ministersOfState": [], "employees": 1197, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/environment", "description": "Responsible for environmental protection, provincial parks and protected areas, and the Environmental Assessment Office."},
  "ministry-of-finance": {"shortName": "FIN", "minister": {"title": "Minister of Finance", "person": "Josie Osborne", "since": "2026-08-14"}, "deputy": {"title": "Deputy Minister (Acting)", "person": "Jonathan Dubé"}, "ministersOfState": [], "employees": 1653, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/finance", "description": "Responsible for the provincial budget, taxation, Treasury Board staff and financial regulation; also houses the BC Public Service Agency, Government Communications and Public Engagement, and the Public Sector Employers' Council Secretariat."},
  "ministry-of-forests": {"shortName": "FOR", "minister": {"title": "Minister of Forests", "person": "Ravi Parmar", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Makenzie Leine"}, "ministersOfState": [], "employees": 4221, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/forests", "description": "Responsible for forest management and the forest sector, including BC Timber Sales and the BC Wildfire Service."},
  "ministry-of-health": {"shortName": "HLTH", "minister": {"title": "Minister of Health", "person": "Ravi Kahlon", "since": "2026-08-14"}, "deputy": {"title": "Deputy Minister", "person": "Cynthia Johansen"}, "ministersOfState": [], "employees": 1676, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/health", "description": "Responsible for the provincial health system, including funding and oversight of the regional health authorities and the Provincial Health Services Authority."},
  "ministry-of-housing-and-municipal-affairs": {"shortName": "HMA", "minister": {"title": "Minister of Housing and Municipal Affairs", "person": "Christine Boyle", "since": "2025-07-17"}, "deputy": {"title": "Deputy Minister", "person": "Teri Collins"}, "ministersOfState": [], "employees": 500, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/housing", "description": "Formed Nov 2024 by merging the Ministry of Housing and the Ministry of Municipal Affairs; responsible for housing policy, municipal infrastructure needs and local-government legislation."},
  "ministry-of-indigenous-relations-and-reconciliation": {"shortName": "IRR", "minister": {"title": "Minister of Indigenous Relations and Reconciliation", "person": "Spencer Chandra Herbert", "since": "2025-07-17"}, "deputy": {"title": "Deputy Minister", "person": "Alex MacLennan"}, "ministersOfState": [], "employees": 258, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/indigenous-relations-reconciliation", "description": "Leads government relationships with Indigenous Peoples, treaty and reconciliation agreements, and implementation of the Declaration on the Rights of Indigenous Peoples Act."},
  "ministry-of-infrastructure": {"shortName": "INF", "minister": {"title": "Minister of Infrastructure", "person": "Bowinn Ma", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Bobbi Plecas"}, "ministersOfState": [], "employees": 105, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/infrastructure", "description": "Created Nov 2024 from the former Ministry of Transportation and Infrastructure; responsible for major capital project planning, procurement and delivery (schools, post-secondary, courthouses, correctional and health facilities), including Infrastructure BC."},
  "ministry-of-jobs-and-economic-growth": {"shortName": "JEG", "minister": {"title": "Minister of Jobs and Economic Growth", "person": "Brenda Bailey", "since": "2026-08-14"}, "deputy": {"title": "Deputy Minister", "person": "Fazil Mihlar"}, "ministersOfState": [{"title": "Minister of State for Artificial Intelligence and New Technologies", "person": "Rick Glumac", "since": "2025-07-17"}], "employees": 289, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/jobs-economic-development-and-innovation", "description": "Renamed from Jobs, Economic Development and Innovation in July 2025; responsible for economic development, major projects, investment and trade diversification. Minister Bailey is on medical leave (from late Aug 2026, expected return early Oct 2026); Adrian Dix is covering the portfolio."},
  "ministry-of-labour": {"shortName": "LBR", "minister": {"title": "Minister of Labour", "person": "Jennifer Whiteside", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Lorie Hrycuik"}, "ministersOfState": [], "employees": 408, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/labour", "description": "Responsible for employment standards, labour relations and workplace safety policy (WorkSafeBC)."},
  "ministry-of-mining-and-critical-minerals": {"shortName": "MCM", "minister": {"title": "Minister of Mining and Critical Minerals", "person": "Jagrup Brar", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Nathaniel Amann-Blake"}, "ministersOfState": [], "employees": 306, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/mining", "description": "Created Nov 2024 (split from Energy, Mines and Low Carbon Innovation); responsible for the provincial mining and critical-minerals strategy and Mineral Tenure Act reform."},
  "ministry-of-post-secondary-education-and-future-skills": {"shortName": "PSFS", "minister": {"title": "Minister of Post-Secondary Education and Future Skills", "person": "Jessie Sunner", "since": "2025-07-17"}, "deputy": {"title": "Deputy Minister", "person": "Trevor Hughes"}, "ministersOfState": [], "employees": 557, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/post-secondary-education-and-future-skills", "description": "Responsible for public post-secondary institutions, skills training, and (since Nov 2024) immigration settlement services. Minister Sunner is on parental leave from July 31, 2026 (expected return Oct 2026); Labour Minister Jennifer Whiteside is covering."},
  "ministry-of-public-safety-and-solicitor-general": {"shortName": "PSSG", "minister": {"title": "Minister of Public Safety and Solicitor General", "person": "Nina Krieger", "since": "2025-07-17"}, "deputy": {"title": "Deputy Solicitor General", "person": "Tara Richards"}, "ministersOfState": [{"title": "Minister of State for Community Safety and Integrated Services", "person": "Terry Yung", "since": "2024-11-18"}], "employees": 3503, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/public-safety-solicitor-general", "description": "Responsible for policing, corrections, victim services and community safety."},
  "ministry-of-social-development-and-poverty-reduction": {"shortName": "SDPR", "minister": {"title": "Minister of Social Development and Poverty Reduction", "person": "Sheila Malcolmson", "since": "2022-12-07"}, "deputy": {"title": "Deputy Minister (Acting)", "person": "Raymond Fieltsch"}, "ministersOfState": [], "employees": 1986, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/social-development-poverty-reduction", "description": "Responsible for income and disability assistance, poverty reduction and accessibility programs."},
  "ministry-of-tourism-arts-culture-and-sport": {"shortName": "TACS", "minister": {"title": "Minister of Tourism, Arts, Culture and Sport", "person": "Anne Kang", "since": "2025-07-17"}, "deputy": {"title": "Deputy Minister", "person": "Silas Brownsey"}, "ministersOfState": [], "employees": 154, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/tourism-arts-culture", "description": "Responsible for tourism, arts, culture, heritage and sport, including major events."},
  "ministry-of-transportation-and-transit": {"shortName": "TT", "minister": {"title": "Minister of Transportation and Transit (and Government House Leader)", "person": "Mike Farnworth", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Heather Wood"}, "ministersOfState": [], "employees": 1470, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/transportation", "description": "Created Nov 2024 from the former Ministry of Transportation and Infrastructure; responsible for provincial highways, transit and transportation networks and major transportation projects."},
  "ministry-of-water-land-and-resource-stewardship": {"shortName": "WLRS", "minister": {"title": "Minister of Water, Land and Resource Stewardship", "person": "Randene Neill", "since": "2024-11-18"}, "deputy": {"title": "Deputy Minister", "person": "Lori Halls"}, "ministersOfState": [], "employees": 1872, "officialUrl": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries/water-land-and-resource-stewardship", "description": "Responsible for land-use planning, water, fish and wildlife stewardship, and Crown land authorizations."}
}

/** Where the facts in this file come from. */
export const CURRENT_SOURCES = [
  {"id": "s-cabinet", "title": "Executive Council and Parliamentary Secretaries of B.C. (last updated Sept 8, 2026)", "url": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/cabinet/cabinet-ministers"},
  {"id": "s-deputies", "title": "Deputy Ministers' Council of British Columbia (last updated July 6, 2026)", "url": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/cabinet/deputy-ministers"},
  {"id": "s-ministries", "title": "Ministries - Province of British Columbia (last updated July 21, 2025)", "url": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/ministries-organizations/ministries"},
  {"id": "s-govstructure", "title": "Government structure - Province of British Columbia", "url": "https://www2.gov.bc.ca/gov/content/governments/organizational-structure"},
  {"id": "s-nov2024", "title": "Premier's new cabinet (news release 2024PREM0067-001590, Nov 18, 2024)", "url": "https://news.gov.bc.ca/releases/2024PREM0067-001590"},
  {"id": "s-jul2025", "title": "Updated cabinet sworn in to meet the needs of British Columbians in a changing world (2025PREM0071-000686, July 17, 2025)", "url": "https://news.gov.bc.ca/releases/2025PREM0071-000686"},
  {"id": "s-aug2026", "title": "Premier announces three cabinet changes (2026PREM0057-000949, Aug 14, 2026)", "url": "https://news.gov.bc.ca/releases/2026PREM0057-000949"},
  {"id": "s-psfs-leave", "title": "Minister of post-secondary education and future skills begins parental leave (2026PSFS0036-000905, July 31, 2026)", "url": "https://news.gov.bc.ca/releases/2026PSFS0036-000905"},
  {"id": "s-wickens-bio", "title": "Honourable Jodie Wickens - biography (BC Gov News)", "url": "https://news.gov.bc.ca/ministries/children-and-family-development/biography"},
  {"id": "s-newsmin", "title": "BC Gov News - ministry pages (minister and minister of state listings)", "url": "https://news.gov.bc.ca/ministries"},
  {"id": "s-ebc2026", "title": "2026 Provincial Election - Elections BC (Writ Day Sept 22, 2026; Final Voting Day Oct 24, 2026)", "url": "https://elections.bc.ca/2026-provincial-election/"},
  {"id": "s-wiki-eby", "title": "Eby ministry - Wikipedia (cross-check)", "url": "https://en.wikipedia.org/wiki/Eby_ministry"},
  {"id": "s-wiki-43", "title": "43rd Parliament of British Columbia - Wikipedia (cross-check; standings at dissolution)", "url": "https://en.wikipedia.org/wiki/43rd_Parliament_of_British_Columbia"},
  {"id": "s-wiki-lg", "title": "List of lieutenant governors of British Columbia - Wikipedia", "url": "https://en.wikipedia.org/wiki/List_of_lieutenant_governors_of_British_Columbia"},
  {"id": "s-bcballot", "title": "BC Legislature seats by party, and every change since 2024 - BC Ballot (as of Sept 23, 2026)", "url": "https://bcballot.ca/updates/"},
  {"id": "crowns-2026", "title": "Crown corporations — Budget 2026 service plans", "url": "https://www.bcbudget.gov.bc.ca/2026/crownserviceplans/"},
  {"id": "crowns-ar-2026", "title": "Crown corporation annual reports 2025/26", "url": "https://www.bcbudget.gov.bc.ca/Annual_Reports/2025_2026/"},
  {"id": "statutory-officers", "title": "Statutory Officers — Legislative Assembly of British Columbia", "url": "https://www.leg.bc.ca/learn/discover-your-legislature/statutory-officers"},
  {"id": "merit-2026", "title": "Merit Commissioner staffing review (2026)", "url": "https://www2.gov.bc.ca/gov/content/careers-myhr/job-seekers/staffing-review/merit-commissioner-staffing-review"},
  {"id": "pa-2025-26", "title": "Public Accounts 2025/26 — Statement of Staff Utilization", "url": "https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/government-finances/public-accounts/2025-26/pa-2025-26-crf-supplementary-schedules.pdf"},
  {"id": "bccourts", "title": "BC Courts", "url": "https://www.bccourts.ca"}
]
