// Flattens the Spirit of BC flag into one set of shapes on its own origin.
//
// The drawing arrives from a vector editor as twelve paths nested in a dozen groups, each carrying
// its own matrix, on an artboard that is mostly empty space. None of that survives here: the
// transforms are baked into the coordinates, the artwork is moved onto its own ink box, and the
// result is twelve flat paths in three colours — the navy, red and gold of the provincial flag.
//
// Run: npm run build:flag

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parsePath, pathBounds } from './svgPath.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const SOURCE = process.env.FLAG_SOURCE ||
  resolve(root, 'artwork/flag/spirit-of-bc-flag.svg')

if (!existsSync(SOURCE)) {
  console.error(
    `\nCould not find the flag artwork at ${SOURCE}.\n` +
    'Point FLAG_SOURCE at the SVG:\n\n' +
    '    FLAG_SOURCE=/path/to/flag.svg npm run build:flag\n')
  process.exit(1)
}

const source = readFileSync(SOURCE, 'utf8')

/** Multiplies two affine matrices given as [a, b, c, d, e, f]. */
const compose = (m, n) => [
  m[0] * n[0] + m[2] * n[1],
  m[1] * n[0] + m[3] * n[1],
  m[0] * n[2] + m[2] * n[3],
  m[1] * n[2] + m[3] * n[3],
  m[0] * n[4] + m[2] * n[5] + m[4],
  m[1] * n[4] + m[3] * n[5] + m[5]
]

const IDENTITY = [1, 0, 0, 1, 0, 0]

const parseMatrix = (text) => {
  const matrix = /matrix\(([^)]*)\)/.exec(text)
  if (matrix) return matrix[1].split(',').map(Number)
  const translate = /translate\(\s*([-\d.]+)[\s,]+([-\d.]+)\s*\)/.exec(text)
  if (translate) return [1, 0, 0, 1, Number(translate[1]), Number(translate[2])]
  return IDENTITY
}

/**
 * Every path in the file, with the transforms of its enclosing groups applied.
 *
 * Walks the markup keeping a stack of matrices, because a path's position is the product of every
 * group above it and there are a dozen of them here — several with a scale, not just a shift.
 */
function flatten (svg) {
  const shapes = []
  const stack = [IDENTITY]

  const token = /<g([^>]*)>|<\/g>|<path([^>]*)\/>/g
  let match

  while ((match = token.exec(svg))) {
    const [whole, groupAttributes, pathAttributes] = match

    if (whole.startsWith('</g')) {
      if (stack.length > 1) stack.pop()
      continue
    }

    if (groupAttributes !== undefined) {
      stack.push(compose(stack.at(-1), parseMatrix(groupAttributes)))
      continue
    }

    const d = /\sd="([^"]+)"/.exec(pathAttributes)?.[1]
    if (!d) continue
    const fill = /fill:\s*(rgb\([^)]*\)|#[0-9a-fA-F]{3,8})/.exec(pathAttributes)?.[1]
    if (!fill || fill === 'none') continue

    shapes.push({ d: apply(d, stack.at(-1)), fill: toHex(fill) })
  }

  return shapes
}

/** Applies a matrix to a path's coordinates. The artwork uses absolute M, L, C and Z only. */
function apply (d, [a, b, c, dd, e, f]) {
  return parsePath(d).map(({ command, values }) => {
    if (command === 'Z' || command === 'z') return 'Z'
    if (!'MLC'.includes(command)) throw new Error(`unexpected path command ${command}`)
    const moved = []
    for (let i = 0; i < values.length; i += 2) {
      const x = values[i]
      const y = values[i + 1]
      moved.push(a * x + c * y + e, b * x + dd * y + f)
    }
    return command + moved.map(round).join(' ').replace(/ -/g, '-')
  }).join('')
}

const round = (value) => String(Math.round(value * 100) / 100).replace(/^(-?)0\./, '$1.')

const toHex = (fill) => {
  const rgb = /rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)/.exec(fill)
  if (!rgb) return fill.toLowerCase()
  return '#' + rgb.slice(1, 4).map((v) => Number(v).toString(16).padStart(2, '0')).join('')
}

const shapes = flatten(source)
if (!shapes.length) {
  console.error('\nNo filled paths found in the artwork.\n')
  process.exit(1)
}

// Onto its own ink box. The artboard is padded, and a lockup has to position the drawing by what
// is actually drawn rather than by whatever margin the editor happened to leave.
let minX = Infinity
let minY = Infinity
let maxX = -Infinity
let maxY = -Infinity
for (const shape of shapes) {
  const box = pathBounds(shape.d)
  minX = Math.min(minX, box.minX)
  minY = Math.min(minY, box.minY)
  maxX = Math.max(maxX, box.maxX)
  maxY = Math.max(maxY, box.maxY)
}

const moved = shapes.map((shape) => ({
  ...shape,
  d: apply(shape.d, [1, 0, 0, 1, -minX, -minY])
}))

const width = Number((maxX - minX).toFixed(2))
const height = Number((maxY - minY).toFixed(2))

const palette = [...new Set(moved.map((shape) => shape.fill))]

writeFileSync(resolve(root, 'src/assets/flagMark.js'), `// Generated by scripts/build-flag.mjs — do not edit.
//
// The Spirit of BC flag, as used in the provincial identity that carried it: a stylised BC flag,
// its Union Jack and setting sun waving over the wordmark's wave bands.
//
// Twelve paths in three colours, with every group transform from the source baked into the
// coordinates and the drawing moved onto its own ink box — so it starts at 0,0 and is exactly as
// wide and tall as what it draws.

export const FLAG = {
  width: ${width},
  height: ${height},
  shapes: [
${moved.map((shape) => `    ${JSON.stringify(shape)}`).join(',\n')}
  ]
}

/** The flag's own colours, in the order they first appear. */
export const FLAG_PALETTE = ${JSON.stringify(palette)}
`)

console.log(`  flag        ${moved.length} shapes, ${palette.length} colours ${palette.join(' ')}`)
console.log(`              ${width} × ${height}  (aspect ${(width / height).toFixed(3)})`)
console.log(`  → src/assets/flagMark.js  (${(JSON.stringify(moved).length / 1024).toFixed(1)} KB)`)
